### ISSUE TITLE
Errors with Shadowlands patch

### ISSUE THREAD

**Issue by Daeveren** [grdn1337/wow-addon-pokemontrainer#10]
Getting errors in patch 9.0:

`...AddOns\PokemonTrainer\Modules\FrameCombatDisplay.lua:434: attempt to call method 'SetBackdropBorderColor' (a nil value)`

`...AddOns\PokemonTrainer\Modules\FrameCombatDisplay.lua:438: attempt to call method 'SetBackdropBorderColor' (a nil value)`

**Comment by GurliGebis** [comment]
Apply the changes from my pull request and reload the UI, then it will work.

**Comment by Daeveren** [comment]
Thanks man, it worked! Thanks a lot!

**Comment by Jrzwolverine** [comment]
I copied the script from the pull request and am still getting this error when I enter the battle:


Message: ...AddOns\PokemonTrainer\Modules\FrameCombatDisplay.lua:294: 'for' limit must be a number
Time: Tue Oct 20 18:14:32 2020
Count: 1
Stack: ...AddOns\PokemonTrainer\Modules\FrameCombatDisplay.lua:294: 'for' limit must be a number
[string "@Interface\AddOns\PokemonTrainer\Modules\FrameCombatDisplay.lua"]:294: in function <...AddOns\PokemonTrainer\Modules\FrameCombatDisplay.lua:290>
[string "@Interface\AddOns\PokemonTrainer\Modules\FrameCombatDisplay.lua"]:316: in function <...AddOns\PokemonTrainer\Modules\FrameCombatDisplay.lua:314>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `Show'
[string "@Interface\AddOns\Blizzard_PetBattleUI\Blizzard_PetBattleUI.lua"]:586: in function `PetBattlePetSelectionFrame_Show'
[string "@Interface\AddOns\Blizzard_PetBattleUI\Blizzard_PetBattleUI.lua"]:183: in function `PetBattleFrame_UpdatePetSelectionFrame'
[string "@Interface\AddOns\Blizzard_PetBattleUI\Blizzard_PetBattleUI.lua"]:155: in function `PetBattleFrame_Display'
[string "@Interface\AddOns\Blizzard_PetBattleUI\Blizzard_PetBattleUI.lua"]:96: in function <...AddOns\Blizzard_PetBattleUI\Blizzard_PetBattleUI.lua:93>

Locals: bigger = true
font = nil
size = nil
outline = nil
fs = nil
(for index) = 1
(for limit) = nil
(for step) = 1
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "'for' limit must be a number"
PT = <table> {
 SetDefaultModuleLibraries = <function> defined @Interface\AddOns\Recount\Libs\AceAddon-3.0\AceAddon-3.0.lua:367
 GetAbilityRamping = <function> defined @Interface\AddOns\PokemonTrainer\Core.lua:646
 Enable = <function> defined @Interface\AddOns\Recount\Libs\AceAddon-3.0\AceAddon-3.0.lua:294
 UnregisterAllEvents = <function> defined @Interface\AddOns\DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
 Data = <table> {
 }
 EnableModule = <function> defined @Interface\AddOns\Recount\Libs\AceAddon-3.0\AceAddon-3.0.lua:332
 modules = <table> {
 }
 GetModule = <function> defined @Interface\AddOns\Recount\Libs\AceAddon-3.0\AceAddon-3.0.lua:210
 IterateEmbeds = <function> defined @Interface\AddOns\Recount\Libs\AceAddon-3.0\AceAddon-3.0.lua:442
 db = <table> {
 }
 defaultModuleLibraries = <table> {
 }
 baseName = "PokemonTrainer"
 PAD_INDEX = 0
 BONUS_SPEED_EQUAL = 1
 BONUS_SPEED_SLOWER = 0
 GetAbilityStateBonuses = <function> defined @Interface\AddOns\PokemonTrainer\Core.lua:602
 GetSpeedBonus = <function> defined @Interface\AddOns\PokemonTrainer\Core.lua:180
 ScanPetAuras = <function> defined @Interface\AddOns\PokemonTrainer\Core.lua:516
 RoundUpPets = <function> defined @Interface\AddOns\PokemonTrainer\Core.lua:489
 GetName = <function> defined @Interface\AddOns\Recount\Libs\AceAddon-3.0\AceAddon-3.0.lua:279
 GetAbilityRampingState = <function> defined @Interface\AddOns\PokemonTrainer\Core.lua:655
 MAX_COMBAT_PETS = 3
 GetTypeBonusIcon = <function> defined @Interface\AddOns\PokemonTrainer\Core.lua:152
 name = "PokemonTrainer"
 PET_INDEX = 1
 IsEnabled = <function> defined @Interface\AddOns\Recount\Libs\AceAddon-3.0\AceAddon-3.0.lua:451
 orderedModules = <table> {
 }
 ScanPets = <function> defined @Interface\AddOns\PokemonTrainer\Core.lua:477
 DisableModule = <function> defined @Interface\AddOns\Recount\Libs\AceAddon-3.0\AceAddon-3.0.lua:350
 GetAbilityCooldown = <function> defined @Interface\AddOns\PokemonTrainer\Core.lua:246
 MAX_PET_ABILITY = 3
 GetTypeIcon = <function> defined @Interface\AddOns\PokemonTrainer\Core.lua:172
 SendMessage = <function> defined @Interface\AddOns\DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:59
 RegisterMessage = <function> defined @Interface\AddOns\DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 UnregisterMessage = <function> defined @Interface\AddOns\DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 IsPVPBattle = <function> defined @Interface\AddOns\PokemonTrainer\Core.lua:133
 WEATHER = 0
 OnEnable = <function> defined @Interface\AddOns\PokemonTra

**Comment by GurliGebis** [comment]
Try and copy the entire contents of the file, and replace the contents of your current file, then restart WoW:

https://raw.githubusercontent.com/GurliGebis/wow-addon-pokemontrainer/Shadowlands/Modules/FrameCombatDisplay.xml

**Comment by tb1337** [comment]
@GurliGebis accepted your pull request and baked your changes into the repo. But I didn't test it due to lacking WoW subscription; hope everything went fine? :)

**Comment by GurliGebis** [comment]
It seems to be working 🙂

**Comment by tb1337** [comment]
Thanks for your support. Think this can be closed 👍
