### ISSUE TITLE
Addon not loading

### ISSUE THREAD

**Issue by Fringetastic** [grdn1337/wow-addon-pokemontrainer#12]
My wife was complaining that this addon won't work for her, so I installed it to see what was going on. 

I have this addon checked to load in the addon screen and I am set to load out of date addons. The first time I loaded in with the addon enabled, I got the welcome message to use /pt to set it up. I used it, it opened the interface, and all seemed good. I did not try a pet battle. That was yesterday but today when I enter a pet battle, PT doesn't come up. The command "/pt" yields the blizzard message "Type '/help' for a ...". In the addon screen, the right column has a "load addon" button. Clicking it doesn't seem to do anything as all of the previous things still happen. It seems the addon isn't loading or triggering?

I disabled all other addons except this one and got the same results. 

Any ideas of why it doesn't load?

**Comment by Fringetastic** [comment]
Later in the evening, after world quests and two Torghast runs, I took a flight path back to the night fae sanctum. When I entered it, I noticed a message from PT: "Recently updated to version 9.1.0". I was able to see PT options in the Interface menu.

**Comment by AmenitradieDruidin** [comment]
Hi, I haven't been loading anything for a long time. Not even with BFA. There was also no update for a loooong time. I think the addon was canceled. Again, there are more and more error messages and unfortunately no answer :(

**Comment by Fringetastic** [comment]
This addon did receive some sort of update a week ago, for background textures. 

I see there several other tickets about this from previous months and years and one of them suggests a workaround: also load the addon arkinventory. This rings a bell so we are going to try that.

**Comment by Fringetastic** [comment]
I found that if I change this in PokemonTrainer.toc:

' ## LoadOnDemand: 1
' ## LoadWith: Blizzard_Collections, Blizzard_PetBattleUI
' ## LoadManagers: AddonLoader
' ## X-LoadOn-Always: delayed

to:
' ## DefaultState: Enabled
' ## LoadOnDemand: 0
' ## LoadManagers: AddonLoader
' ## X-LoadOn-Always: delayed'

Then PT always loads and I can battle with it. However, it causes a lua error when loading in:
'1x ...ceBlizzard_Collections\Blizzard_Wardrobe.lua:3027: bad argument #2 to 'format' (string expected, got nil)'

I don't know what I'm doing so if anyone tries this, keep that in mind! We will try using this change and see how it goes.

**Comment by tb1337** [comment]
Please note that PT was configured to load on demand to prevent this LUA error. But, yeah, PT is not ready for Shadowlands and currently there are no plans to update it. Didn't feed actual pet data for years and therefore, I think its better for you to move on.

**Comment by tb1337** [comment]
> Hi, I haven't been loading anything for a long time. Not even with BFA. There was also no update for a loooong time. I think the addon was canceled. Again, there are more and more error messages and unfortunately no answer :(

Here I am, answering you :) Please have a look at my above post.

**Comment by Fringetastic** [comment]
Thanks for the response, I appreciate it. I relayed the news to my wife, who is now quite disappointed. Apparently the missing pet data didn't matter to her. She really liked and misses the grids on the sides showing when abilities will be available.

P.S. I'm glad I gave up on trying to get around that lua error! If you couldn't do it, I'd never be able to. =D

**Comment by tb1337** [comment]
Please tell your wife that it makes me a really sad panda when she is unhappy now. I will get a subscription during the christmas holiday and check what has to be done in order to get PT running again. Do we have a deal?

**Comment by AmenitradieDruidin** [comment]
I thank you for the answer. But I almost thought so. Thanks anyway for the great addon :)

**Comment by tb1337** [comment]
I'll take a look into the issues. Really didn't know that there are still people using the mod and especially, making pet battles. I will reply when there are news ready to be shared.

**Comment by Fringetastic** [comment]
Edit:
That's too good of a deal - I'll gift you the month. To gift game time, looks like your email address is needed. I may be missing how to send PMs on this platform but I can't find it. I'm on twitter @frngtstc if you want to DM it; I have not been checking twitter but I will for this. 

Also, my wife was amazed you're willing take a look. "it's like a christmas present!"   That said, if it doesn't work out, we really do understand. 😃

**Comment by tb1337** [comment]
Due to the above explained Lua errors, PT loads on demand with Blizzard_Collections and Blizzard_PetBattleUI of the Blizzard user interface. You have to open your pet collections tab once (shift + p) in order to get PT loaded. Then everything is fine.

Could you deal with it?

**Comment by tb1337** [comment]
Forget what I said... I will release version 9.0.0 now. Built a simple Loader for your wife. PokemonTrainer now will load when hovering battle pets with the mouse or entering /pt in the chat, in addition to pressing shift + p.

Can you give me some feedback please? Tested it locally and it works fine.

**Comment by Fringetastic** [comment]
Hi. She tried out the update last night on some old pet battles and some new battle pets in shadowlands and everything worked perfectly. The UI pulled up without any special actions and the abilities of both teams were populated. Thank you very much! Is there anything else you'd like to see tested?

**Comment by tb1337** [comment]
That's fine, thank you! :-)

**Comment by tb1337** [comment]
Fringetastic, would you contact me under dev@grdn.rocks ? I have a question :)
