### ISSUE TITLE
9.0 UnitIsBattlePet nil

### ISSUE THREAD

**Issue by SteveKnowless** [grdn1337/wow-addon-pokemontrainer#13]
Updated to the latest version this morning and I am getting this error over and over. Thanks

211x PokemonTrainer_Loader\Loader.lua:32: Usage: UnitIsBattlePet("unit")
[string "=[C]"]: in function `UnitIsBattlePet'
[string "@PokemonTrainer_Loader\Loader.lua"]:32: in function <PokemonTrainer_Loader\Loader.lua:17>

Locals:
(*temporary) = nil

**Comment by tb1337** [comment]
Recently published and updated version. You should check your addons, there must be a reason for you having empty tooltip mouseover events (UPDATE_MOUSEOVER_UNIT).
