### ISSUE TITLE
Addon not loading  :(

### ISSUE THREAD

**Issue by AmenitradieDruidin** [grdn1337/wow-addon-pokemontrainer#6]
Hello, I downloaded the addon. But it will not load. The addon will be displayed. (see picture) But I'm not in the settings. Not on the chat (/pt) and not on the interface menu. Also do not see that the addon is active.
What can this be? Am I doing something wrong?

https://i.imgur.com/QvXoxCX.jpg
![h](https://user-images.githubusercontent.com/39033070/62408956-98080c00-b5d0-11e9-83a3-4ab90654b3da.jpg)

**Comment by AmenitradieDruidin** [comment]
Ok, that's funny. I have no ad for fighting. But in PVP pet fighting.
And when I come from the PVP fight, I come back into the settings. So it loads, sometimes not.
And if I do a reload, I will not be in the settings again.
Do not know if the information will help?

**Comment by Walkerbo** [comment]
This is what is happening to me also.
I have disabled all other addons, then I check the in game interface there is no page for the addon.
/pt does not work at all.

**Comment by tb1337** [comment]
Version 9.0.0 will load on typing /pt, hovering battle pets or pressing shift+p.
