### ISSUE TITLE
Add-on will NOT load

### ISSUE THREAD

**Issue by sbeanamb** [grdn1337/wow-addon-pokemontrainer#8]
I love this mod; however, it simply won't load. Even after uninstalling, deleting the settings files, and reinstalling.
The add-on is checked in the Add-on Menu at the character screen. In game, the add-on shows as " Only loadable on demand." When I start a pet battle, the add-on doesn't load. I exit the battle, click "Load" and "ReloadUI" and nothing happens. I return to the Add-on menu and it's still greyed out and not loaded.

This issue seems to be the same issue that's been reported a few times already.

Thanks so much for looking into this.

**Comment by AmenitradieDruidin** [comment]
Yes, I have the same problem.

**Comment by Walkerbo** [comment]
Same here

**Comment by tb1337** [comment]
Version 9.0.0 will now load on typing /pt, hovering battle pets with the mouse or by pressing shift + p.
